packages:
  - "."
  - "api-server"
  - "packages/*"

catalog:
  "@replit/vite-plugin-cartographer": "^0.3.1"
  "@replit/vite-plugin-dev-banner": "^0.1.2"
  "@replit/vite-plugin-runtime-error-modal": "^0.0.3"
  "@tailwindcss/vite": "^4.1.3"
  "@tanstack/react-query": "^5.74.4"
  "@types/node": "^22.14.0"
  "@types/react": "^19.1.0"
  "@types/react-dom": "^19.1.2"
  "@vitejs/plugin-react": "^4.3.4"
  "class-variance-authority": "^0.7.1"
  "clsx": "^2.1.1"
  "drizzle-orm": "^0.43.0"
  "framer-motion": "^12.6.5"
  "lucide-react": "^0.487.0"
  "react": "^19.1.0"
  "react-dom": "^19.1.0"
  "tailwind-merge": "^3.2.0"
  "tailwindcss": "^4.1.3"
  "tsx": "^4.19.3"
  "vite": "^6.3.1"
  "zod": "^3.24.2"
